/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompanySlugRouteRouteImport } from './routes/$companySlug/route'
import { Route as CompanySlugLoginRouteImport } from './routes/$companySlug/login'
import { Route as CompanySlugErrorRouteImport } from './routes/$companySlug/error'
import { Route as CompanySlugAccessDeniedRouteImport } from './routes/$companySlug/access-denied'
import { Route as CompanySlugAuthedRouteImport } from './routes/$companySlug/_authed'
import { Route as CompanySlugAuthWorkosCallbackRouteImport } from './routes/$companySlug/auth/workos-callback'
import { Route as CompanySlugAuthConfirmRouteImport } from './routes/$companySlug/auth/confirm'
import { Route as CompanySlugAuthedAccountRouteImport } from './routes/$companySlug/_authed/account'
import { Route as CompanySlugAuthedWmsRouteRouteImport } from './routes/$companySlug/_authed/wms/route'
import { Route as CompanySlugAuthedPmRouteRouteImport } from './routes/$companySlug/_authed/pm/route'
import { Route as CompanySlugAuthedPlmRouteRouteImport } from './routes/$companySlug/_authed/plm/route'
import { Route as CompanySlugAuthedErpRouteRouteImport } from './routes/$companySlug/_authed/erp/route'
import { Route as CompanySlugAuthedCrmRouteRouteImport } from './routes/$companySlug/_authed/crm/route'
import { Route as CompanySlugAuthedHomeRouteRouteImport } from './routes/$companySlug/_authed/_home/route'
import { Route as CompanySlugAuthedWmsIndexRouteImport } from './routes/$companySlug/_authed/wms/index'
import { Route as CompanySlugAuthedPmIndexRouteImport } from './routes/$companySlug/_authed/pm/index'
import { Route as CompanySlugAuthedPlmIndexRouteImport } from './routes/$companySlug/_authed/plm/index'
import { Route as CompanySlugAuthedErpIndexRouteImport } from './routes/$companySlug/_authed/erp/index'
import { Route as CompanySlugAuthedCrmIndexRouteImport } from './routes/$companySlug/_authed/crm/index'
import { Route as CompanySlugAuthedHomeIndexRouteImport } from './routes/$companySlug/_authed/_home/index'
import { Route as CompanySlugAuthedWmsInventoryRouteImport } from './routes/$companySlug/_authed/wms/inventory'
import { Route as CompanySlugAuthedWmsAllocationRouteImport } from './routes/$companySlug/_authed/wms/allocation'
import { Route as CompanySlugAuthedPlmVariantsRouteImport } from './routes/$companySlug/_authed/plm/variants'
import { Route as CompanySlugAuthedErpVendorsRouteImport } from './routes/$companySlug/_authed/erp/vendors'
import { Route as CompanySlugAuthedErpSalesChannelsRouteImport } from './routes/$companySlug/_authed/erp/sales-channels'
import { Route as CompanySlugAuthedErpAllocationRequestsRouteImport } from './routes/$companySlug/_authed/erp/allocation-requests'
import { Route as CompanySlugAuthedHomeTeamRouteImport } from './routes/$companySlug/_authed/_home/team'
import { Route as CompanySlugAuthedHomeDashboardRouteImport } from './routes/$companySlug/_authed/_home/dashboard'
import { Route as CompanySlugAuthedWmsOrdersIndexRouteImport } from './routes/$companySlug/_authed/wms/orders/index'
import { Route as CompanySlugAuthedPmProjectsIndexRouteImport } from './routes/$companySlug/_authed/pm/projects/index'
import { Route as CompanySlugAuthedPmCampaignsIndexRouteImport } from './routes/$companySlug/_authed/pm/campaigns/index'
import { Route as CompanySlugAuthedPlmSourcingIndexRouteImport } from './routes/$companySlug/_authed/plm/sourcing/index'
import { Route as CompanySlugAuthedPlmProductsIndexRouteImport } from './routes/$companySlug/_authed/plm/products/index'
import { Route as CompanySlugAuthedErpPurchaseOrdersIndexRouteImport } from './routes/$companySlug/_authed/erp/purchase-orders/index'
import { Route as CompanySlugAuthedCrmCustomersIndexRouteImport } from './routes/$companySlug/_authed/crm/customers/index'
import { Route as CompanySlugAuthedCrmAllocationOrdersIndexRouteImport } from './routes/$companySlug/_authed/crm/allocation-orders/index'
import { Route as CompanySlugAuthedWmsOrdersIdRouteImport } from './routes/$companySlug/_authed/wms/orders/$id'
import { Route as CompanySlugAuthedPmProjectsProjectIdRouteImport } from './routes/$companySlug/_authed/pm/projects/$projectId'
import { Route as CompanySlugAuthedPmCampaignsNewRouteImport } from './routes/$companySlug/_authed/pm/campaigns/new'
import { Route as CompanySlugAuthedPmCampaignsCampaignIdRouteImport } from './routes/$companySlug/_authed/pm/campaigns/$campaignId'
import { Route as CompanySlugAuthedPlmSourcingNewRouteImport } from './routes/$companySlug/_authed/plm/sourcing/new'
import { Route as CompanySlugAuthedPlmSourcingSourcingIdRouteImport } from './routes/$companySlug/_authed/plm/sourcing/$sourcingId'
import { Route as CompanySlugAuthedPlmProductsNewRouteImport } from './routes/$companySlug/_authed/plm/products/new'
import { Route as CompanySlugAuthedPlmProductsProductIdRouteImport } from './routes/$companySlug/_authed/plm/products/$productId'
import { Route as CompanySlugAuthedErpPurchaseOrdersNewRouteImport } from './routes/$companySlug/_authed/erp/purchase-orders/new'
import { Route as CompanySlugAuthedCrmCustomersIdRouteImport } from './routes/$companySlug/_authed/crm/customers/$id'
import { Route as CompanySlugAuthedCrmAllocationOrdersNewRouteImport } from './routes/$companySlug/_authed/crm/allocation-orders/new'
import { Route as CompanySlugAuthedErpPurchaseOrdersIdIndexRouteImport } from './routes/$companySlug/_authed/erp/purchase-orders/$id/index'
import { Route as CompanySlugAuthedErpFinanceExpensesIndexRouteImport } from './routes/$companySlug/_authed/erp/finance/expenses/index'
import { Route as CompanySlugAuthedErpPurchaseOrdersIdEditRouteImport } from './routes/$companySlug/_authed/erp/purchase-orders/$id/edit'

const CompanySlugRouteRoute = CompanySlugRouteRouteImport.update({
  id: '/$companySlug',
  path: '/$companySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugLoginRoute = CompanySlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugErrorRoute = CompanySlugErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugAccessDeniedRoute = CompanySlugAccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugAuthedRoute = CompanySlugAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugAuthWorkosCallbackRoute =
  CompanySlugAuthWorkosCallbackRouteImport.update({
    id: '/auth/workos-callback',
    path: '/auth/workos-callback',
    getParentRoute: () => CompanySlugRouteRoute,
  } as any)
const CompanySlugAuthConfirmRoute = CompanySlugAuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => CompanySlugRouteRoute,
} as any)
const CompanySlugAuthedAccountRoute =
  CompanySlugAuthedAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => CompanySlugAuthedRoute,
  } as any)
const CompanySlugAuthedWmsRouteRoute =
  CompanySlugAuthedWmsRouteRouteImport.update({
    id: '/wms',
    path: '/wms',
    getParentRoute: () => CompanySlugAuthedRoute,
  } as any)
const CompanySlugAuthedPmRouteRoute =
  CompanySlugAuthedPmRouteRouteImport.update({
    id: '/pm',
    path: '/pm',
    getParentRoute: () => CompanySlugAuthedRoute,
  } as any)
const CompanySlugAuthedPlmRouteRoute =
  CompanySlugAuthedPlmRouteRouteImport.update({
    id: '/plm',
    path: '/plm',
    getParentRoute: () => CompanySlugAuthedRoute,
  } as any)
const CompanySlugAuthedErpRouteRoute =
  CompanySlugAuthedErpRouteRouteImport.update({
    id: '/erp',
    path: '/erp',
    getParentRoute: () => CompanySlugAuthedRoute,
  } as any)
const CompanySlugAuthedCrmRouteRoute =
  CompanySlugAuthedCrmRouteRouteImport.update({
    id: '/crm',
    path: '/crm',
    getParentRoute: () => CompanySlugAuthedRoute,
  } as any)
const CompanySlugAuthedHomeRouteRoute =
  CompanySlugAuthedHomeRouteRouteImport.update({
    id: '/_home',
    getParentRoute: () => CompanySlugAuthedRoute,
  } as any)
const CompanySlugAuthedWmsIndexRoute =
  CompanySlugAuthedWmsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugAuthedWmsRouteRoute,
  } as any)
const CompanySlugAuthedPmIndexRoute =
  CompanySlugAuthedPmIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugAuthedPmRouteRoute,
  } as any)
const CompanySlugAuthedPlmIndexRoute =
  CompanySlugAuthedPlmIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugAuthedPlmRouteRoute,
  } as any)
const CompanySlugAuthedErpIndexRoute =
  CompanySlugAuthedErpIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugAuthedErpRouteRoute,
  } as any)
const CompanySlugAuthedCrmIndexRoute =
  CompanySlugAuthedCrmIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugAuthedCrmRouteRoute,
  } as any)
const CompanySlugAuthedHomeIndexRoute =
  CompanySlugAuthedHomeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CompanySlugAuthedHomeRouteRoute,
  } as any)
const CompanySlugAuthedWmsInventoryRoute =
  CompanySlugAuthedWmsInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => CompanySlugAuthedWmsRouteRoute,
  } as any)
const CompanySlugAuthedWmsAllocationRoute =
  CompanySlugAuthedWmsAllocationRouteImport.update({
    id: '/allocation',
    path: '/allocation',
    getParentRoute: () => CompanySlugAuthedWmsRouteRoute,
  } as any)
const CompanySlugAuthedPlmVariantsRoute =
  CompanySlugAuthedPlmVariantsRouteImport.update({
    id: '/variants',
    path: '/variants',
    getParentRoute: () => CompanySlugAuthedPlmRouteRoute,
  } as any)
const CompanySlugAuthedErpVendorsRoute =
  CompanySlugAuthedErpVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => CompanySlugAuthedErpRouteRoute,
  } as any)
const CompanySlugAuthedErpSalesChannelsRoute =
  CompanySlugAuthedErpSalesChannelsRouteImport.update({
    id: '/sales-channels',
    path: '/sales-channels',
    getParentRoute: () => CompanySlugAuthedErpRouteRoute,
  } as any)
const CompanySlugAuthedErpAllocationRequestsRoute =
  CompanySlugAuthedErpAllocationRequestsRouteImport.update({
    id: '/allocation-requests',
    path: '/allocation-requests',
    getParentRoute: () => CompanySlugAuthedErpRouteRoute,
  } as any)
const CompanySlugAuthedHomeTeamRoute =
  CompanySlugAuthedHomeTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => CompanySlugAuthedHomeRouteRoute,
  } as any)
const CompanySlugAuthedHomeDashboardRoute =
  CompanySlugAuthedHomeDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => CompanySlugAuthedHomeRouteRoute,
  } as any)
const CompanySlugAuthedWmsOrdersIndexRoute =
  CompanySlugAuthedWmsOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => CompanySlugAuthedWmsRouteRoute,
  } as any)
const CompanySlugAuthedPmProjectsIndexRoute =
  CompanySlugAuthedPmProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => CompanySlugAuthedPmRouteRoute,
  } as any)
const CompanySlugAuthedPmCampaignsIndexRoute =
  CompanySlugAuthedPmCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => CompanySlugAuthedPmRouteRoute,
  } as any)
const CompanySlugAuthedPlmSourcingIndexRoute =
  CompanySlugAuthedPlmSourcingIndexRouteImport.update({
    id: '/sourcing/',
    path: '/sourcing/',
    getParentRoute: () => CompanySlugAuthedPlmRouteRoute,
  } as any)
const CompanySlugAuthedPlmProductsIndexRoute =
  CompanySlugAuthedPlmProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => CompanySlugAuthedPlmRouteRoute,
  } as any)
const CompanySlugAuthedErpPurchaseOrdersIndexRoute =
  CompanySlugAuthedErpPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => CompanySlugAuthedErpRouteRoute,
  } as any)
const CompanySlugAuthedCrmCustomersIndexRoute =
  CompanySlugAuthedCrmCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => CompanySlugAuthedCrmRouteRoute,
  } as any)
const CompanySlugAuthedCrmAllocationOrdersIndexRoute =
  CompanySlugAuthedCrmAllocationOrdersIndexRouteImport.update({
    id: '/allocation-orders/',
    path: '/allocation-orders/',
    getParentRoute: () => CompanySlugAuthedCrmRouteRoute,
  } as any)
const CompanySlugAuthedWmsOrdersIdRoute =
  CompanySlugAuthedWmsOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => CompanySlugAuthedWmsRouteRoute,
  } as any)
const CompanySlugAuthedPmProjectsProjectIdRoute =
  CompanySlugAuthedPmProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => CompanySlugAuthedPmRouteRoute,
  } as any)
const CompanySlugAuthedPmCampaignsNewRoute =
  CompanySlugAuthedPmCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => CompanySlugAuthedPmRouteRoute,
  } as any)
const CompanySlugAuthedPmCampaignsCampaignIdRoute =
  CompanySlugAuthedPmCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => CompanySlugAuthedPmRouteRoute,
  } as any)
const CompanySlugAuthedPlmSourcingNewRoute =
  CompanySlugAuthedPlmSourcingNewRouteImport.update({
    id: '/sourcing/new',
    path: '/sourcing/new',
    getParentRoute: () => CompanySlugAuthedPlmRouteRoute,
  } as any)
const CompanySlugAuthedPlmSourcingSourcingIdRoute =
  CompanySlugAuthedPlmSourcingSourcingIdRouteImport.update({
    id: '/sourcing/$sourcingId',
    path: '/sourcing/$sourcingId',
    getParentRoute: () => CompanySlugAuthedPlmRouteRoute,
  } as any)
const CompanySlugAuthedPlmProductsNewRoute =
  CompanySlugAuthedPlmProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => CompanySlugAuthedPlmRouteRoute,
  } as any)
const CompanySlugAuthedPlmProductsProductIdRoute =
  CompanySlugAuthedPlmProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => CompanySlugAuthedPlmRouteRoute,
  } as any)
const CompanySlugAuthedErpPurchaseOrdersNewRoute =
  CompanySlugAuthedErpPurchaseOrdersNewRouteImport.update({
    id: '/purchase-orders/new',
    path: '/purchase-orders/new',
    getParentRoute: () => CompanySlugAuthedErpRouteRoute,
  } as any)
const CompanySlugAuthedCrmCustomersIdRoute =
  CompanySlugAuthedCrmCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => CompanySlugAuthedCrmRouteRoute,
  } as any)
const CompanySlugAuthedCrmAllocationOrdersNewRoute =
  CompanySlugAuthedCrmAllocationOrdersNewRouteImport.update({
    id: '/allocation-orders/new',
    path: '/allocation-orders/new',
    getParentRoute: () => CompanySlugAuthedCrmRouteRoute,
  } as any)
const CompanySlugAuthedErpPurchaseOrdersIdIndexRoute =
  CompanySlugAuthedErpPurchaseOrdersIdIndexRouteImport.update({
    id: '/purchase-orders/$id/',
    path: '/purchase-orders/$id/',
    getParentRoute: () => CompanySlugAuthedErpRouteRoute,
  } as any)
const CompanySlugAuthedErpFinanceExpensesIndexRoute =
  CompanySlugAuthedErpFinanceExpensesIndexRouteImport.update({
    id: '/finance/expenses/',
    path: '/finance/expenses/',
    getParentRoute: () => CompanySlugAuthedErpRouteRoute,
  } as any)
const CompanySlugAuthedErpPurchaseOrdersIdEditRoute =
  CompanySlugAuthedErpPurchaseOrdersIdEditRouteImport.update({
    id: '/purchase-orders/$id/edit',
    path: '/purchase-orders/$id/edit',
    getParentRoute: () => CompanySlugAuthedErpRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$companySlug': typeof CompanySlugRouteRouteWithChildren
  '/$companySlug/access-denied': typeof CompanySlugAccessDeniedRoute
  '/$companySlug/error': typeof CompanySlugErrorRoute
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/$companySlug/crm': typeof CompanySlugAuthedCrmRouteRouteWithChildren
  '/$companySlug/erp': typeof CompanySlugAuthedErpRouteRouteWithChildren
  '/$companySlug/plm': typeof CompanySlugAuthedPlmRouteRouteWithChildren
  '/$companySlug/pm': typeof CompanySlugAuthedPmRouteRouteWithChildren
  '/$companySlug/wms': typeof CompanySlugAuthedWmsRouteRouteWithChildren
  '/$companySlug/account': typeof CompanySlugAuthedAccountRoute
  '/$companySlug/auth/confirm': typeof CompanySlugAuthConfirmRoute
  '/$companySlug/auth/workos-callback': typeof CompanySlugAuthWorkosCallbackRoute
  '/$companySlug/dashboard': typeof CompanySlugAuthedHomeDashboardRoute
  '/$companySlug/team': typeof CompanySlugAuthedHomeTeamRoute
  '/$companySlug/erp/allocation-requests': typeof CompanySlugAuthedErpAllocationRequestsRoute
  '/$companySlug/erp/sales-channels': typeof CompanySlugAuthedErpSalesChannelsRoute
  '/$companySlug/erp/vendors': typeof CompanySlugAuthedErpVendorsRoute
  '/$companySlug/plm/variants': typeof CompanySlugAuthedPlmVariantsRoute
  '/$companySlug/wms/allocation': typeof CompanySlugAuthedWmsAllocationRoute
  '/$companySlug/wms/inventory': typeof CompanySlugAuthedWmsInventoryRoute
  '/$companySlug/': typeof CompanySlugAuthedHomeIndexRoute
  '/$companySlug/crm/': typeof CompanySlugAuthedCrmIndexRoute
  '/$companySlug/erp/': typeof CompanySlugAuthedErpIndexRoute
  '/$companySlug/plm/': typeof CompanySlugAuthedPlmIndexRoute
  '/$companySlug/pm/': typeof CompanySlugAuthedPmIndexRoute
  '/$companySlug/wms/': typeof CompanySlugAuthedWmsIndexRoute
  '/$companySlug/crm/allocation-orders/new': typeof CompanySlugAuthedCrmAllocationOrdersNewRoute
  '/$companySlug/crm/customers/$id': typeof CompanySlugAuthedCrmCustomersIdRoute
  '/$companySlug/erp/purchase-orders/new': typeof CompanySlugAuthedErpPurchaseOrdersNewRoute
  '/$companySlug/plm/products/$productId': typeof CompanySlugAuthedPlmProductsProductIdRoute
  '/$companySlug/plm/products/new': typeof CompanySlugAuthedPlmProductsNewRoute
  '/$companySlug/plm/sourcing/$sourcingId': typeof CompanySlugAuthedPlmSourcingSourcingIdRoute
  '/$companySlug/plm/sourcing/new': typeof CompanySlugAuthedPlmSourcingNewRoute
  '/$companySlug/pm/campaigns/$campaignId': typeof CompanySlugAuthedPmCampaignsCampaignIdRoute
  '/$companySlug/pm/campaigns/new': typeof CompanySlugAuthedPmCampaignsNewRoute
  '/$companySlug/pm/projects/$projectId': typeof CompanySlugAuthedPmProjectsProjectIdRoute
  '/$companySlug/wms/orders/$id': typeof CompanySlugAuthedWmsOrdersIdRoute
  '/$companySlug/crm/allocation-orders/': typeof CompanySlugAuthedCrmAllocationOrdersIndexRoute
  '/$companySlug/crm/customers/': typeof CompanySlugAuthedCrmCustomersIndexRoute
  '/$companySlug/erp/purchase-orders/': typeof CompanySlugAuthedErpPurchaseOrdersIndexRoute
  '/$companySlug/plm/products/': typeof CompanySlugAuthedPlmProductsIndexRoute
  '/$companySlug/plm/sourcing/': typeof CompanySlugAuthedPlmSourcingIndexRoute
  '/$companySlug/pm/campaigns/': typeof CompanySlugAuthedPmCampaignsIndexRoute
  '/$companySlug/pm/projects/': typeof CompanySlugAuthedPmProjectsIndexRoute
  '/$companySlug/wms/orders/': typeof CompanySlugAuthedWmsOrdersIndexRoute
  '/$companySlug/erp/purchase-orders/$id/edit': typeof CompanySlugAuthedErpPurchaseOrdersIdEditRoute
  '/$companySlug/erp/finance/expenses/': typeof CompanySlugAuthedErpFinanceExpensesIndexRoute
  '/$companySlug/erp/purchase-orders/$id/': typeof CompanySlugAuthedErpPurchaseOrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/$companySlug': typeof CompanySlugAuthedHomeIndexRoute
  '/$companySlug/access-denied': typeof CompanySlugAccessDeniedRoute
  '/$companySlug/error': typeof CompanySlugErrorRoute
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/$companySlug/account': typeof CompanySlugAuthedAccountRoute
  '/$companySlug/auth/confirm': typeof CompanySlugAuthConfirmRoute
  '/$companySlug/auth/workos-callback': typeof CompanySlugAuthWorkosCallbackRoute
  '/$companySlug/dashboard': typeof CompanySlugAuthedHomeDashboardRoute
  '/$companySlug/team': typeof CompanySlugAuthedHomeTeamRoute
  '/$companySlug/erp/allocation-requests': typeof CompanySlugAuthedErpAllocationRequestsRoute
  '/$companySlug/erp/sales-channels': typeof CompanySlugAuthedErpSalesChannelsRoute
  '/$companySlug/erp/vendors': typeof CompanySlugAuthedErpVendorsRoute
  '/$companySlug/plm/variants': typeof CompanySlugAuthedPlmVariantsRoute
  '/$companySlug/wms/allocation': typeof CompanySlugAuthedWmsAllocationRoute
  '/$companySlug/wms/inventory': typeof CompanySlugAuthedWmsInventoryRoute
  '/$companySlug/crm': typeof CompanySlugAuthedCrmIndexRoute
  '/$companySlug/erp': typeof CompanySlugAuthedErpIndexRoute
  '/$companySlug/plm': typeof CompanySlugAuthedPlmIndexRoute
  '/$companySlug/pm': typeof CompanySlugAuthedPmIndexRoute
  '/$companySlug/wms': typeof CompanySlugAuthedWmsIndexRoute
  '/$companySlug/crm/allocation-orders/new': typeof CompanySlugAuthedCrmAllocationOrdersNewRoute
  '/$companySlug/crm/customers/$id': typeof CompanySlugAuthedCrmCustomersIdRoute
  '/$companySlug/erp/purchase-orders/new': typeof CompanySlugAuthedErpPurchaseOrdersNewRoute
  '/$companySlug/plm/products/$productId': typeof CompanySlugAuthedPlmProductsProductIdRoute
  '/$companySlug/plm/products/new': typeof CompanySlugAuthedPlmProductsNewRoute
  '/$companySlug/plm/sourcing/$sourcingId': typeof CompanySlugAuthedPlmSourcingSourcingIdRoute
  '/$companySlug/plm/sourcing/new': typeof CompanySlugAuthedPlmSourcingNewRoute
  '/$companySlug/pm/campaigns/$campaignId': typeof CompanySlugAuthedPmCampaignsCampaignIdRoute
  '/$companySlug/pm/campaigns/new': typeof CompanySlugAuthedPmCampaignsNewRoute
  '/$companySlug/pm/projects/$projectId': typeof CompanySlugAuthedPmProjectsProjectIdRoute
  '/$companySlug/wms/orders/$id': typeof CompanySlugAuthedWmsOrdersIdRoute
  '/$companySlug/crm/allocation-orders': typeof CompanySlugAuthedCrmAllocationOrdersIndexRoute
  '/$companySlug/crm/customers': typeof CompanySlugAuthedCrmCustomersIndexRoute
  '/$companySlug/erp/purchase-orders': typeof CompanySlugAuthedErpPurchaseOrdersIndexRoute
  '/$companySlug/plm/products': typeof CompanySlugAuthedPlmProductsIndexRoute
  '/$companySlug/plm/sourcing': typeof CompanySlugAuthedPlmSourcingIndexRoute
  '/$companySlug/pm/campaigns': typeof CompanySlugAuthedPmCampaignsIndexRoute
  '/$companySlug/pm/projects': typeof CompanySlugAuthedPmProjectsIndexRoute
  '/$companySlug/wms/orders': typeof CompanySlugAuthedWmsOrdersIndexRoute
  '/$companySlug/erp/purchase-orders/$id/edit': typeof CompanySlugAuthedErpPurchaseOrdersIdEditRoute
  '/$companySlug/erp/finance/expenses': typeof CompanySlugAuthedErpFinanceExpensesIndexRoute
  '/$companySlug/erp/purchase-orders/$id': typeof CompanySlugAuthedErpPurchaseOrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$companySlug': typeof CompanySlugRouteRouteWithChildren
  '/$companySlug/_authed': typeof CompanySlugAuthedRouteWithChildren
  '/$companySlug/access-denied': typeof CompanySlugAccessDeniedRoute
  '/$companySlug/error': typeof CompanySlugErrorRoute
  '/$companySlug/login': typeof CompanySlugLoginRoute
  '/$companySlug/_authed/_home': typeof CompanySlugAuthedHomeRouteRouteWithChildren
  '/$companySlug/_authed/crm': typeof CompanySlugAuthedCrmRouteRouteWithChildren
  '/$companySlug/_authed/erp': typeof CompanySlugAuthedErpRouteRouteWithChildren
  '/$companySlug/_authed/plm': typeof CompanySlugAuthedPlmRouteRouteWithChildren
  '/$companySlug/_authed/pm': typeof CompanySlugAuthedPmRouteRouteWithChildren
  '/$companySlug/_authed/wms': typeof CompanySlugAuthedWmsRouteRouteWithChildren
  '/$companySlug/_authed/account': typeof CompanySlugAuthedAccountRoute
  '/$companySlug/auth/confirm': typeof CompanySlugAuthConfirmRoute
  '/$companySlug/auth/workos-callback': typeof CompanySlugAuthWorkosCallbackRoute
  '/$companySlug/_authed/_home/dashboard': typeof CompanySlugAuthedHomeDashboardRoute
  '/$companySlug/_authed/_home/team': typeof CompanySlugAuthedHomeTeamRoute
  '/$companySlug/_authed/erp/allocation-requests': typeof CompanySlugAuthedErpAllocationRequestsRoute
  '/$companySlug/_authed/erp/sales-channels': typeof CompanySlugAuthedErpSalesChannelsRoute
  '/$companySlug/_authed/erp/vendors': typeof CompanySlugAuthedErpVendorsRoute
  '/$companySlug/_authed/plm/variants': typeof CompanySlugAuthedPlmVariantsRoute
  '/$companySlug/_authed/wms/allocation': typeof CompanySlugAuthedWmsAllocationRoute
  '/$companySlug/_authed/wms/inventory': typeof CompanySlugAuthedWmsInventoryRoute
  '/$companySlug/_authed/_home/': typeof CompanySlugAuthedHomeIndexRoute
  '/$companySlug/_authed/crm/': typeof CompanySlugAuthedCrmIndexRoute
  '/$companySlug/_authed/erp/': typeof CompanySlugAuthedErpIndexRoute
  '/$companySlug/_authed/plm/': typeof CompanySlugAuthedPlmIndexRoute
  '/$companySlug/_authed/pm/': typeof CompanySlugAuthedPmIndexRoute
  '/$companySlug/_authed/wms/': typeof CompanySlugAuthedWmsIndexRoute
  '/$companySlug/_authed/crm/allocation-orders/new': typeof CompanySlugAuthedCrmAllocationOrdersNewRoute
  '/$companySlug/_authed/crm/customers/$id': typeof CompanySlugAuthedCrmCustomersIdRoute
  '/$companySlug/_authed/erp/purchase-orders/new': typeof CompanySlugAuthedErpPurchaseOrdersNewRoute
  '/$companySlug/_authed/plm/products/$productId': typeof CompanySlugAuthedPlmProductsProductIdRoute
  '/$companySlug/_authed/plm/products/new': typeof CompanySlugAuthedPlmProductsNewRoute
  '/$companySlug/_authed/plm/sourcing/$sourcingId': typeof CompanySlugAuthedPlmSourcingSourcingIdRoute
  '/$companySlug/_authed/plm/sourcing/new': typeof CompanySlugAuthedPlmSourcingNewRoute
  '/$companySlug/_authed/pm/campaigns/$campaignId': typeof CompanySlugAuthedPmCampaignsCampaignIdRoute
  '/$companySlug/_authed/pm/campaigns/new': typeof CompanySlugAuthedPmCampaignsNewRoute
  '/$companySlug/_authed/pm/projects/$projectId': typeof CompanySlugAuthedPmProjectsProjectIdRoute
  '/$companySlug/_authed/wms/orders/$id': typeof CompanySlugAuthedWmsOrdersIdRoute
  '/$companySlug/_authed/crm/allocation-orders/': typeof CompanySlugAuthedCrmAllocationOrdersIndexRoute
  '/$companySlug/_authed/crm/customers/': typeof CompanySlugAuthedCrmCustomersIndexRoute
  '/$companySlug/_authed/erp/purchase-orders/': typeof CompanySlugAuthedErpPurchaseOrdersIndexRoute
  '/$companySlug/_authed/plm/products/': typeof CompanySlugAuthedPlmProductsIndexRoute
  '/$companySlug/_authed/plm/sourcing/': typeof CompanySlugAuthedPlmSourcingIndexRoute
  '/$companySlug/_authed/pm/campaigns/': typeof CompanySlugAuthedPmCampaignsIndexRoute
  '/$companySlug/_authed/pm/projects/': typeof CompanySlugAuthedPmProjectsIndexRoute
  '/$companySlug/_authed/wms/orders/': typeof CompanySlugAuthedWmsOrdersIndexRoute
  '/$companySlug/_authed/erp/purchase-orders/$id/edit': typeof CompanySlugAuthedErpPurchaseOrdersIdEditRoute
  '/$companySlug/_authed/erp/finance/expenses/': typeof CompanySlugAuthedErpFinanceExpensesIndexRoute
  '/$companySlug/_authed/erp/purchase-orders/$id/': typeof CompanySlugAuthedErpPurchaseOrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$companySlug'
    | '/$companySlug/access-denied'
    | '/$companySlug/error'
    | '/$companySlug/login'
    | '/$companySlug/crm'
    | '/$companySlug/erp'
    | '/$companySlug/plm'
    | '/$companySlug/pm'
    | '/$companySlug/wms'
    | '/$companySlug/account'
    | '/$companySlug/auth/confirm'
    | '/$companySlug/auth/workos-callback'
    | '/$companySlug/dashboard'
    | '/$companySlug/team'
    | '/$companySlug/erp/allocation-requests'
    | '/$companySlug/erp/sales-channels'
    | '/$companySlug/erp/vendors'
    | '/$companySlug/plm/variants'
    | '/$companySlug/wms/allocation'
    | '/$companySlug/wms/inventory'
    | '/$companySlug/'
    | '/$companySlug/crm/'
    | '/$companySlug/erp/'
    | '/$companySlug/plm/'
    | '/$companySlug/pm/'
    | '/$companySlug/wms/'
    | '/$companySlug/crm/allocation-orders/new'
    | '/$companySlug/crm/customers/$id'
    | '/$companySlug/erp/purchase-orders/new'
    | '/$companySlug/plm/products/$productId'
    | '/$companySlug/plm/products/new'
    | '/$companySlug/plm/sourcing/$sourcingId'
    | '/$companySlug/plm/sourcing/new'
    | '/$companySlug/pm/campaigns/$campaignId'
    | '/$companySlug/pm/campaigns/new'
    | '/$companySlug/pm/projects/$projectId'
    | '/$companySlug/wms/orders/$id'
    | '/$companySlug/crm/allocation-orders/'
    | '/$companySlug/crm/customers/'
    | '/$companySlug/erp/purchase-orders/'
    | '/$companySlug/plm/products/'
    | '/$companySlug/plm/sourcing/'
    | '/$companySlug/pm/campaigns/'
    | '/$companySlug/pm/projects/'
    | '/$companySlug/wms/orders/'
    | '/$companySlug/erp/purchase-orders/$id/edit'
    | '/$companySlug/erp/finance/expenses/'
    | '/$companySlug/erp/purchase-orders/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$companySlug'
    | '/$companySlug/access-denied'
    | '/$companySlug/error'
    | '/$companySlug/login'
    | '/$companySlug/account'
    | '/$companySlug/auth/confirm'
    | '/$companySlug/auth/workos-callback'
    | '/$companySlug/dashboard'
    | '/$companySlug/team'
    | '/$companySlug/erp/allocation-requests'
    | '/$companySlug/erp/sales-channels'
    | '/$companySlug/erp/vendors'
    | '/$companySlug/plm/variants'
    | '/$companySlug/wms/allocation'
    | '/$companySlug/wms/inventory'
    | '/$companySlug/crm'
    | '/$companySlug/erp'
    | '/$companySlug/plm'
    | '/$companySlug/pm'
    | '/$companySlug/wms'
    | '/$companySlug/crm/allocation-orders/new'
    | '/$companySlug/crm/customers/$id'
    | '/$companySlug/erp/purchase-orders/new'
    | '/$companySlug/plm/products/$productId'
    | '/$companySlug/plm/products/new'
    | '/$companySlug/plm/sourcing/$sourcingId'
    | '/$companySlug/plm/sourcing/new'
    | '/$companySlug/pm/campaigns/$campaignId'
    | '/$companySlug/pm/campaigns/new'
    | '/$companySlug/pm/projects/$projectId'
    | '/$companySlug/wms/orders/$id'
    | '/$companySlug/crm/allocation-orders'
    | '/$companySlug/crm/customers'
    | '/$companySlug/erp/purchase-orders'
    | '/$companySlug/plm/products'
    | '/$companySlug/plm/sourcing'
    | '/$companySlug/pm/campaigns'
    | '/$companySlug/pm/projects'
    | '/$companySlug/wms/orders'
    | '/$companySlug/erp/purchase-orders/$id/edit'
    | '/$companySlug/erp/finance/expenses'
    | '/$companySlug/erp/purchase-orders/$id'
  id:
    | '__root__'
    | '/$companySlug'
    | '/$companySlug/_authed'
    | '/$companySlug/access-denied'
    | '/$companySlug/error'
    | '/$companySlug/login'
    | '/$companySlug/_authed/_home'
    | '/$companySlug/_authed/crm'
    | '/$companySlug/_authed/erp'
    | '/$companySlug/_authed/plm'
    | '/$companySlug/_authed/pm'
    | '/$companySlug/_authed/wms'
    | '/$companySlug/_authed/account'
    | '/$companySlug/auth/confirm'
    | '/$companySlug/auth/workos-callback'
    | '/$companySlug/_authed/_home/dashboard'
    | '/$companySlug/_authed/_home/team'
    | '/$companySlug/_authed/erp/allocation-requests'
    | '/$companySlug/_authed/erp/sales-channels'
    | '/$companySlug/_authed/erp/vendors'
    | '/$companySlug/_authed/plm/variants'
    | '/$companySlug/_authed/wms/allocation'
    | '/$companySlug/_authed/wms/inventory'
    | '/$companySlug/_authed/_home/'
    | '/$companySlug/_authed/crm/'
    | '/$companySlug/_authed/erp/'
    | '/$companySlug/_authed/plm/'
    | '/$companySlug/_authed/pm/'
    | '/$companySlug/_authed/wms/'
    | '/$companySlug/_authed/crm/allocation-orders/new'
    | '/$companySlug/_authed/crm/customers/$id'
    | '/$companySlug/_authed/erp/purchase-orders/new'
    | '/$companySlug/_authed/plm/products/$productId'
    | '/$companySlug/_authed/plm/products/new'
    | '/$companySlug/_authed/plm/sourcing/$sourcingId'
    | '/$companySlug/_authed/plm/sourcing/new'
    | '/$companySlug/_authed/pm/campaigns/$campaignId'
    | '/$companySlug/_authed/pm/campaigns/new'
    | '/$companySlug/_authed/pm/projects/$projectId'
    | '/$companySlug/_authed/wms/orders/$id'
    | '/$companySlug/_authed/crm/allocation-orders/'
    | '/$companySlug/_authed/crm/customers/'
    | '/$companySlug/_authed/erp/purchase-orders/'
    | '/$companySlug/_authed/plm/products/'
    | '/$companySlug/_authed/plm/sourcing/'
    | '/$companySlug/_authed/pm/campaigns/'
    | '/$companySlug/_authed/pm/projects/'
    | '/$companySlug/_authed/wms/orders/'
    | '/$companySlug/_authed/erp/purchase-orders/$id/edit'
    | '/$companySlug/_authed/erp/finance/expenses/'
    | '/$companySlug/_authed/erp/purchase-orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CompanySlugRouteRoute: typeof CompanySlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$companySlug': {
      id: '/$companySlug'
      path: '/$companySlug'
      fullPath: '/$companySlug'
      preLoaderRoute: typeof CompanySlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$companySlug/login': {
      id: '/$companySlug/login'
      path: '/login'
      fullPath: '/$companySlug/login'
      preLoaderRoute: typeof CompanySlugLoginRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/error': {
      id: '/$companySlug/error'
      path: '/error'
      fullPath: '/$companySlug/error'
      preLoaderRoute: typeof CompanySlugErrorRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/access-denied': {
      id: '/$companySlug/access-denied'
      path: '/access-denied'
      fullPath: '/$companySlug/access-denied'
      preLoaderRoute: typeof CompanySlugAccessDeniedRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/_authed': {
      id: '/$companySlug/_authed'
      path: ''
      fullPath: '/$companySlug'
      preLoaderRoute: typeof CompanySlugAuthedRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/auth/workos-callback': {
      id: '/$companySlug/auth/workos-callback'
      path: '/auth/workos-callback'
      fullPath: '/$companySlug/auth/workos-callback'
      preLoaderRoute: typeof CompanySlugAuthWorkosCallbackRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/auth/confirm': {
      id: '/$companySlug/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/$companySlug/auth/confirm'
      preLoaderRoute: typeof CompanySlugAuthConfirmRouteImport
      parentRoute: typeof CompanySlugRouteRoute
    }
    '/$companySlug/_authed/account': {
      id: '/$companySlug/_authed/account'
      path: '/account'
      fullPath: '/$companySlug/account'
      preLoaderRoute: typeof CompanySlugAuthedAccountRouteImport
      parentRoute: typeof CompanySlugAuthedRoute
    }
    '/$companySlug/_authed/wms': {
      id: '/$companySlug/_authed/wms'
      path: '/wms'
      fullPath: '/$companySlug/wms'
      preLoaderRoute: typeof CompanySlugAuthedWmsRouteRouteImport
      parentRoute: typeof CompanySlugAuthedRoute
    }
    '/$companySlug/_authed/pm': {
      id: '/$companySlug/_authed/pm'
      path: '/pm'
      fullPath: '/$companySlug/pm'
      preLoaderRoute: typeof CompanySlugAuthedPmRouteRouteImport
      parentRoute: typeof CompanySlugAuthedRoute
    }
    '/$companySlug/_authed/plm': {
      id: '/$companySlug/_authed/plm'
      path: '/plm'
      fullPath: '/$companySlug/plm'
      preLoaderRoute: typeof CompanySlugAuthedPlmRouteRouteImport
      parentRoute: typeof CompanySlugAuthedRoute
    }
    '/$companySlug/_authed/erp': {
      id: '/$companySlug/_authed/erp'
      path: '/erp'
      fullPath: '/$companySlug/erp'
      preLoaderRoute: typeof CompanySlugAuthedErpRouteRouteImport
      parentRoute: typeof CompanySlugAuthedRoute
    }
    '/$companySlug/_authed/crm': {
      id: '/$companySlug/_authed/crm'
      path: '/crm'
      fullPath: '/$companySlug/crm'
      preLoaderRoute: typeof CompanySlugAuthedCrmRouteRouteImport
      parentRoute: typeof CompanySlugAuthedRoute
    }
    '/$companySlug/_authed/_home': {
      id: '/$companySlug/_authed/_home'
      path: ''
      fullPath: '/$companySlug'
      preLoaderRoute: typeof CompanySlugAuthedHomeRouteRouteImport
      parentRoute: typeof CompanySlugAuthedRoute
    }
    '/$companySlug/_authed/wms/': {
      id: '/$companySlug/_authed/wms/'
      path: '/'
      fullPath: '/$companySlug/wms/'
      preLoaderRoute: typeof CompanySlugAuthedWmsIndexRouteImport
      parentRoute: typeof CompanySlugAuthedWmsRouteRoute
    }
    '/$companySlug/_authed/pm/': {
      id: '/$companySlug/_authed/pm/'
      path: '/'
      fullPath: '/$companySlug/pm/'
      preLoaderRoute: typeof CompanySlugAuthedPmIndexRouteImport
      parentRoute: typeof CompanySlugAuthedPmRouteRoute
    }
    '/$companySlug/_authed/plm/': {
      id: '/$companySlug/_authed/plm/'
      path: '/'
      fullPath: '/$companySlug/plm/'
      preLoaderRoute: typeof CompanySlugAuthedPlmIndexRouteImport
      parentRoute: typeof CompanySlugAuthedPlmRouteRoute
    }
    '/$companySlug/_authed/erp/': {
      id: '/$companySlug/_authed/erp/'
      path: '/'
      fullPath: '/$companySlug/erp/'
      preLoaderRoute: typeof CompanySlugAuthedErpIndexRouteImport
      parentRoute: typeof CompanySlugAuthedErpRouteRoute
    }
    '/$companySlug/_authed/crm/': {
      id: '/$companySlug/_authed/crm/'
      path: '/'
      fullPath: '/$companySlug/crm/'
      preLoaderRoute: typeof CompanySlugAuthedCrmIndexRouteImport
      parentRoute: typeof CompanySlugAuthedCrmRouteRoute
    }
    '/$companySlug/_authed/_home/': {
      id: '/$companySlug/_authed/_home/'
      path: '/'
      fullPath: '/$companySlug/'
      preLoaderRoute: typeof CompanySlugAuthedHomeIndexRouteImport
      parentRoute: typeof CompanySlugAuthedHomeRouteRoute
    }
    '/$companySlug/_authed/wms/inventory': {
      id: '/$companySlug/_authed/wms/inventory'
      path: '/inventory'
      fullPath: '/$companySlug/wms/inventory'
      preLoaderRoute: typeof CompanySlugAuthedWmsInventoryRouteImport
      parentRoute: typeof CompanySlugAuthedWmsRouteRoute
    }
    '/$companySlug/_authed/wms/allocation': {
      id: '/$companySlug/_authed/wms/allocation'
      path: '/allocation'
      fullPath: '/$companySlug/wms/allocation'
      preLoaderRoute: typeof CompanySlugAuthedWmsAllocationRouteImport
      parentRoute: typeof CompanySlugAuthedWmsRouteRoute
    }
    '/$companySlug/_authed/plm/variants': {
      id: '/$companySlug/_authed/plm/variants'
      path: '/variants'
      fullPath: '/$companySlug/plm/variants'
      preLoaderRoute: typeof CompanySlugAuthedPlmVariantsRouteImport
      parentRoute: typeof CompanySlugAuthedPlmRouteRoute
    }
    '/$companySlug/_authed/erp/vendors': {
      id: '/$companySlug/_authed/erp/vendors'
      path: '/vendors'
      fullPath: '/$companySlug/erp/vendors'
      preLoaderRoute: typeof CompanySlugAuthedErpVendorsRouteImport
      parentRoute: typeof CompanySlugAuthedErpRouteRoute
    }
    '/$companySlug/_authed/erp/sales-channels': {
      id: '/$companySlug/_authed/erp/sales-channels'
      path: '/sales-channels'
      fullPath: '/$companySlug/erp/sales-channels'
      preLoaderRoute: typeof CompanySlugAuthedErpSalesChannelsRouteImport
      parentRoute: typeof CompanySlugAuthedErpRouteRoute
    }
    '/$companySlug/_authed/erp/allocation-requests': {
      id: '/$companySlug/_authed/erp/allocation-requests'
      path: '/allocation-requests'
      fullPath: '/$companySlug/erp/allocation-requests'
      preLoaderRoute: typeof CompanySlugAuthedErpAllocationRequestsRouteImport
      parentRoute: typeof CompanySlugAuthedErpRouteRoute
    }
    '/$companySlug/_authed/_home/team': {
      id: '/$companySlug/_authed/_home/team'
      path: '/team'
      fullPath: '/$companySlug/team'
      preLoaderRoute: typeof CompanySlugAuthedHomeTeamRouteImport
      parentRoute: typeof CompanySlugAuthedHomeRouteRoute
    }
    '/$companySlug/_authed/_home/dashboard': {
      id: '/$companySlug/_authed/_home/dashboard'
      path: '/dashboard'
      fullPath: '/$companySlug/dashboard'
      preLoaderRoute: typeof CompanySlugAuthedHomeDashboardRouteImport
      parentRoute: typeof CompanySlugAuthedHomeRouteRoute
    }
    '/$companySlug/_authed/wms/orders/': {
      id: '/$companySlug/_authed/wms/orders/'
      path: '/orders'
      fullPath: '/$companySlug/wms/orders/'
      preLoaderRoute: typeof CompanySlugAuthedWmsOrdersIndexRouteImport
      parentRoute: typeof CompanySlugAuthedWmsRouteRoute
    }
    '/$companySlug/_authed/pm/projects/': {
      id: '/$companySlug/_authed/pm/projects/'
      path: '/projects'
      fullPath: '/$companySlug/pm/projects/'
      preLoaderRoute: typeof CompanySlugAuthedPmProjectsIndexRouteImport
      parentRoute: typeof CompanySlugAuthedPmRouteRoute
    }
    '/$companySlug/_authed/pm/campaigns/': {
      id: '/$companySlug/_authed/pm/campaigns/'
      path: '/campaigns'
      fullPath: '/$companySlug/pm/campaigns/'
      preLoaderRoute: typeof CompanySlugAuthedPmCampaignsIndexRouteImport
      parentRoute: typeof CompanySlugAuthedPmRouteRoute
    }
    '/$companySlug/_authed/plm/sourcing/': {
      id: '/$companySlug/_authed/plm/sourcing/'
      path: '/sourcing'
      fullPath: '/$companySlug/plm/sourcing/'
      preLoaderRoute: typeof CompanySlugAuthedPlmSourcingIndexRouteImport
      parentRoute: typeof CompanySlugAuthedPlmRouteRoute
    }
    '/$companySlug/_authed/plm/products/': {
      id: '/$companySlug/_authed/plm/products/'
      path: '/products'
      fullPath: '/$companySlug/plm/products/'
      preLoaderRoute: typeof CompanySlugAuthedPlmProductsIndexRouteImport
      parentRoute: typeof CompanySlugAuthedPlmRouteRoute
    }
    '/$companySlug/_authed/erp/purchase-orders/': {
      id: '/$companySlug/_authed/erp/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/$companySlug/erp/purchase-orders/'
      preLoaderRoute: typeof CompanySlugAuthedErpPurchaseOrdersIndexRouteImport
      parentRoute: typeof CompanySlugAuthedErpRouteRoute
    }
    '/$companySlug/_authed/crm/customers/': {
      id: '/$companySlug/_authed/crm/customers/'
      path: '/customers'
      fullPath: '/$companySlug/crm/customers/'
      preLoaderRoute: typeof CompanySlugAuthedCrmCustomersIndexRouteImport
      parentRoute: typeof CompanySlugAuthedCrmRouteRoute
    }
    '/$companySlug/_authed/crm/allocation-orders/': {
      id: '/$companySlug/_authed/crm/allocation-orders/'
      path: '/allocation-orders'
      fullPath: '/$companySlug/crm/allocation-orders/'
      preLoaderRoute: typeof CompanySlugAuthedCrmAllocationOrdersIndexRouteImport
      parentRoute: typeof CompanySlugAuthedCrmRouteRoute
    }
    '/$companySlug/_authed/wms/orders/$id': {
      id: '/$companySlug/_authed/wms/orders/$id'
      path: '/orders/$id'
      fullPath: '/$companySlug/wms/orders/$id'
      preLoaderRoute: typeof CompanySlugAuthedWmsOrdersIdRouteImport
      parentRoute: typeof CompanySlugAuthedWmsRouteRoute
    }
    '/$companySlug/_authed/pm/projects/$projectId': {
      id: '/$companySlug/_authed/pm/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$companySlug/pm/projects/$projectId'
      preLoaderRoute: typeof CompanySlugAuthedPmProjectsProjectIdRouteImport
      parentRoute: typeof CompanySlugAuthedPmRouteRoute
    }
    '/$companySlug/_authed/pm/campaigns/new': {
      id: '/$companySlug/_authed/pm/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/$companySlug/pm/campaigns/new'
      preLoaderRoute: typeof CompanySlugAuthedPmCampaignsNewRouteImport
      parentRoute: typeof CompanySlugAuthedPmRouteRoute
    }
    '/$companySlug/_authed/pm/campaigns/$campaignId': {
      id: '/$companySlug/_authed/pm/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/$companySlug/pm/campaigns/$campaignId'
      preLoaderRoute: typeof CompanySlugAuthedPmCampaignsCampaignIdRouteImport
      parentRoute: typeof CompanySlugAuthedPmRouteRoute
    }
    '/$companySlug/_authed/plm/sourcing/new': {
      id: '/$companySlug/_authed/plm/sourcing/new'
      path: '/sourcing/new'
      fullPath: '/$companySlug/plm/sourcing/new'
      preLoaderRoute: typeof CompanySlugAuthedPlmSourcingNewRouteImport
      parentRoute: typeof CompanySlugAuthedPlmRouteRoute
    }
    '/$companySlug/_authed/plm/sourcing/$sourcingId': {
      id: '/$companySlug/_authed/plm/sourcing/$sourcingId'
      path: '/sourcing/$sourcingId'
      fullPath: '/$companySlug/plm/sourcing/$sourcingId'
      preLoaderRoute: typeof CompanySlugAuthedPlmSourcingSourcingIdRouteImport
      parentRoute: typeof CompanySlugAuthedPlmRouteRoute
    }
    '/$companySlug/_authed/plm/products/new': {
      id: '/$companySlug/_authed/plm/products/new'
      path: '/products/new'
      fullPath: '/$companySlug/plm/products/new'
      preLoaderRoute: typeof CompanySlugAuthedPlmProductsNewRouteImport
      parentRoute: typeof CompanySlugAuthedPlmRouteRoute
    }
    '/$companySlug/_authed/plm/products/$productId': {
      id: '/$companySlug/_authed/plm/products/$productId'
      path: '/products/$productId'
      fullPath: '/$companySlug/plm/products/$productId'
      preLoaderRoute: typeof CompanySlugAuthedPlmProductsProductIdRouteImport
      parentRoute: typeof CompanySlugAuthedPlmRouteRoute
    }
    '/$companySlug/_authed/erp/purchase-orders/new': {
      id: '/$companySlug/_authed/erp/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/$companySlug/erp/purchase-orders/new'
      preLoaderRoute: typeof CompanySlugAuthedErpPurchaseOrdersNewRouteImport
      parentRoute: typeof CompanySlugAuthedErpRouteRoute
    }
    '/$companySlug/_authed/crm/customers/$id': {
      id: '/$companySlug/_authed/crm/customers/$id'
      path: '/customers/$id'
      fullPath: '/$companySlug/crm/customers/$id'
      preLoaderRoute: typeof CompanySlugAuthedCrmCustomersIdRouteImport
      parentRoute: typeof CompanySlugAuthedCrmRouteRoute
    }
    '/$companySlug/_authed/crm/allocation-orders/new': {
      id: '/$companySlug/_authed/crm/allocation-orders/new'
      path: '/allocation-orders/new'
      fullPath: '/$companySlug/crm/allocation-orders/new'
      preLoaderRoute: typeof CompanySlugAuthedCrmAllocationOrdersNewRouteImport
      parentRoute: typeof CompanySlugAuthedCrmRouteRoute
    }
    '/$companySlug/_authed/erp/purchase-orders/$id/': {
      id: '/$companySlug/_authed/erp/purchase-orders/$id/'
      path: '/purchase-orders/$id'
      fullPath: '/$companySlug/erp/purchase-orders/$id/'
      preLoaderRoute: typeof CompanySlugAuthedErpPurchaseOrdersIdIndexRouteImport
      parentRoute: typeof CompanySlugAuthedErpRouteRoute
    }
    '/$companySlug/_authed/erp/finance/expenses/': {
      id: '/$companySlug/_authed/erp/finance/expenses/'
      path: '/finance/expenses'
      fullPath: '/$companySlug/erp/finance/expenses/'
      preLoaderRoute: typeof CompanySlugAuthedErpFinanceExpensesIndexRouteImport
      parentRoute: typeof CompanySlugAuthedErpRouteRoute
    }
    '/$companySlug/_authed/erp/purchase-orders/$id/edit': {
      id: '/$companySlug/_authed/erp/purchase-orders/$id/edit'
      path: '/purchase-orders/$id/edit'
      fullPath: '/$companySlug/erp/purchase-orders/$id/edit'
      preLoaderRoute: typeof CompanySlugAuthedErpPurchaseOrdersIdEditRouteImport
      parentRoute: typeof CompanySlugAuthedErpRouteRoute
    }
  }
}

interface CompanySlugAuthedHomeRouteRouteChildren {
  CompanySlugAuthedHomeDashboardRoute: typeof CompanySlugAuthedHomeDashboardRoute
  CompanySlugAuthedHomeTeamRoute: typeof CompanySlugAuthedHomeTeamRoute
  CompanySlugAuthedHomeIndexRoute: typeof CompanySlugAuthedHomeIndexRoute
}

const CompanySlugAuthedHomeRouteRouteChildren: CompanySlugAuthedHomeRouteRouteChildren =
  {
    CompanySlugAuthedHomeDashboardRoute: CompanySlugAuthedHomeDashboardRoute,
    CompanySlugAuthedHomeTeamRoute: CompanySlugAuthedHomeTeamRoute,
    CompanySlugAuthedHomeIndexRoute: CompanySlugAuthedHomeIndexRoute,
  }

const CompanySlugAuthedHomeRouteRouteWithChildren =
  CompanySlugAuthedHomeRouteRoute._addFileChildren(
    CompanySlugAuthedHomeRouteRouteChildren,
  )

interface CompanySlugAuthedCrmRouteRouteChildren {
  CompanySlugAuthedCrmIndexRoute: typeof CompanySlugAuthedCrmIndexRoute
  CompanySlugAuthedCrmAllocationOrdersNewRoute: typeof CompanySlugAuthedCrmAllocationOrdersNewRoute
  CompanySlugAuthedCrmCustomersIdRoute: typeof CompanySlugAuthedCrmCustomersIdRoute
  CompanySlugAuthedCrmAllocationOrdersIndexRoute: typeof CompanySlugAuthedCrmAllocationOrdersIndexRoute
  CompanySlugAuthedCrmCustomersIndexRoute: typeof CompanySlugAuthedCrmCustomersIndexRoute
}

const CompanySlugAuthedCrmRouteRouteChildren: CompanySlugAuthedCrmRouteRouteChildren =
  {
    CompanySlugAuthedCrmIndexRoute: CompanySlugAuthedCrmIndexRoute,
    CompanySlugAuthedCrmAllocationOrdersNewRoute:
      CompanySlugAuthedCrmAllocationOrdersNewRoute,
    CompanySlugAuthedCrmCustomersIdRoute: CompanySlugAuthedCrmCustomersIdRoute,
    CompanySlugAuthedCrmAllocationOrdersIndexRoute:
      CompanySlugAuthedCrmAllocationOrdersIndexRoute,
    CompanySlugAuthedCrmCustomersIndexRoute:
      CompanySlugAuthedCrmCustomersIndexRoute,
  }

const CompanySlugAuthedCrmRouteRouteWithChildren =
  CompanySlugAuthedCrmRouteRoute._addFileChildren(
    CompanySlugAuthedCrmRouteRouteChildren,
  )

interface CompanySlugAuthedErpRouteRouteChildren {
  CompanySlugAuthedErpAllocationRequestsRoute: typeof CompanySlugAuthedErpAllocationRequestsRoute
  CompanySlugAuthedErpSalesChannelsRoute: typeof CompanySlugAuthedErpSalesChannelsRoute
  CompanySlugAuthedErpVendorsRoute: typeof CompanySlugAuthedErpVendorsRoute
  CompanySlugAuthedErpIndexRoute: typeof CompanySlugAuthedErpIndexRoute
  CompanySlugAuthedErpPurchaseOrdersNewRoute: typeof CompanySlugAuthedErpPurchaseOrdersNewRoute
  CompanySlugAuthedErpPurchaseOrdersIndexRoute: typeof CompanySlugAuthedErpPurchaseOrdersIndexRoute
  CompanySlugAuthedErpPurchaseOrdersIdEditRoute: typeof CompanySlugAuthedErpPurchaseOrdersIdEditRoute
  CompanySlugAuthedErpFinanceExpensesIndexRoute: typeof CompanySlugAuthedErpFinanceExpensesIndexRoute
  CompanySlugAuthedErpPurchaseOrdersIdIndexRoute: typeof CompanySlugAuthedErpPurchaseOrdersIdIndexRoute
}

const CompanySlugAuthedErpRouteRouteChildren: CompanySlugAuthedErpRouteRouteChildren =
  {
    CompanySlugAuthedErpAllocationRequestsRoute:
      CompanySlugAuthedErpAllocationRequestsRoute,
    CompanySlugAuthedErpSalesChannelsRoute:
      CompanySlugAuthedErpSalesChannelsRoute,
    CompanySlugAuthedErpVendorsRoute: CompanySlugAuthedErpVendorsRoute,
    CompanySlugAuthedErpIndexRoute: CompanySlugAuthedErpIndexRoute,
    CompanySlugAuthedErpPurchaseOrdersNewRoute:
      CompanySlugAuthedErpPurchaseOrdersNewRoute,
    CompanySlugAuthedErpPurchaseOrdersIndexRoute:
      CompanySlugAuthedErpPurchaseOrdersIndexRoute,
    CompanySlugAuthedErpPurchaseOrdersIdEditRoute:
      CompanySlugAuthedErpPurchaseOrdersIdEditRoute,
    CompanySlugAuthedErpFinanceExpensesIndexRoute:
      CompanySlugAuthedErpFinanceExpensesIndexRoute,
    CompanySlugAuthedErpPurchaseOrdersIdIndexRoute:
      CompanySlugAuthedErpPurchaseOrdersIdIndexRoute,
  }

const CompanySlugAuthedErpRouteRouteWithChildren =
  CompanySlugAuthedErpRouteRoute._addFileChildren(
    CompanySlugAuthedErpRouteRouteChildren,
  )

interface CompanySlugAuthedPlmRouteRouteChildren {
  CompanySlugAuthedPlmVariantsRoute: typeof CompanySlugAuthedPlmVariantsRoute
  CompanySlugAuthedPlmIndexRoute: typeof CompanySlugAuthedPlmIndexRoute
  CompanySlugAuthedPlmProductsProductIdRoute: typeof CompanySlugAuthedPlmProductsProductIdRoute
  CompanySlugAuthedPlmProductsNewRoute: typeof CompanySlugAuthedPlmProductsNewRoute
  CompanySlugAuthedPlmSourcingSourcingIdRoute: typeof CompanySlugAuthedPlmSourcingSourcingIdRoute
  CompanySlugAuthedPlmSourcingNewRoute: typeof CompanySlugAuthedPlmSourcingNewRoute
  CompanySlugAuthedPlmProductsIndexRoute: typeof CompanySlugAuthedPlmProductsIndexRoute
  CompanySlugAuthedPlmSourcingIndexRoute: typeof CompanySlugAuthedPlmSourcingIndexRoute
}

const CompanySlugAuthedPlmRouteRouteChildren: CompanySlugAuthedPlmRouteRouteChildren =
  {
    CompanySlugAuthedPlmVariantsRoute: CompanySlugAuthedPlmVariantsRoute,
    CompanySlugAuthedPlmIndexRoute: CompanySlugAuthedPlmIndexRoute,
    CompanySlugAuthedPlmProductsProductIdRoute:
      CompanySlugAuthedPlmProductsProductIdRoute,
    CompanySlugAuthedPlmProductsNewRoute: CompanySlugAuthedPlmProductsNewRoute,
    CompanySlugAuthedPlmSourcingSourcingIdRoute:
      CompanySlugAuthedPlmSourcingSourcingIdRoute,
    CompanySlugAuthedPlmSourcingNewRoute: CompanySlugAuthedPlmSourcingNewRoute,
    CompanySlugAuthedPlmProductsIndexRoute:
      CompanySlugAuthedPlmProductsIndexRoute,
    CompanySlugAuthedPlmSourcingIndexRoute:
      CompanySlugAuthedPlmSourcingIndexRoute,
  }

const CompanySlugAuthedPlmRouteRouteWithChildren =
  CompanySlugAuthedPlmRouteRoute._addFileChildren(
    CompanySlugAuthedPlmRouteRouteChildren,
  )

interface CompanySlugAuthedPmRouteRouteChildren {
  CompanySlugAuthedPmIndexRoute: typeof CompanySlugAuthedPmIndexRoute
  CompanySlugAuthedPmCampaignsCampaignIdRoute: typeof CompanySlugAuthedPmCampaignsCampaignIdRoute
  CompanySlugAuthedPmCampaignsNewRoute: typeof CompanySlugAuthedPmCampaignsNewRoute
  CompanySlugAuthedPmProjectsProjectIdRoute: typeof CompanySlugAuthedPmProjectsProjectIdRoute
  CompanySlugAuthedPmCampaignsIndexRoute: typeof CompanySlugAuthedPmCampaignsIndexRoute
  CompanySlugAuthedPmProjectsIndexRoute: typeof CompanySlugAuthedPmProjectsIndexRoute
}

const CompanySlugAuthedPmRouteRouteChildren: CompanySlugAuthedPmRouteRouteChildren =
  {
    CompanySlugAuthedPmIndexRoute: CompanySlugAuthedPmIndexRoute,
    CompanySlugAuthedPmCampaignsCampaignIdRoute:
      CompanySlugAuthedPmCampaignsCampaignIdRoute,
    CompanySlugAuthedPmCampaignsNewRoute: CompanySlugAuthedPmCampaignsNewRoute,
    CompanySlugAuthedPmProjectsProjectIdRoute:
      CompanySlugAuthedPmProjectsProjectIdRoute,
    CompanySlugAuthedPmCampaignsIndexRoute:
      CompanySlugAuthedPmCampaignsIndexRoute,
    CompanySlugAuthedPmProjectsIndexRoute:
      CompanySlugAuthedPmProjectsIndexRoute,
  }

const CompanySlugAuthedPmRouteRouteWithChildren =
  CompanySlugAuthedPmRouteRoute._addFileChildren(
    CompanySlugAuthedPmRouteRouteChildren,
  )

interface CompanySlugAuthedWmsRouteRouteChildren {
  CompanySlugAuthedWmsAllocationRoute: typeof CompanySlugAuthedWmsAllocationRoute
  CompanySlugAuthedWmsInventoryRoute: typeof CompanySlugAuthedWmsInventoryRoute
  CompanySlugAuthedWmsIndexRoute: typeof CompanySlugAuthedWmsIndexRoute
  CompanySlugAuthedWmsOrdersIdRoute: typeof CompanySlugAuthedWmsOrdersIdRoute
  CompanySlugAuthedWmsOrdersIndexRoute: typeof CompanySlugAuthedWmsOrdersIndexRoute
}

const CompanySlugAuthedWmsRouteRouteChildren: CompanySlugAuthedWmsRouteRouteChildren =
  {
    CompanySlugAuthedWmsAllocationRoute: CompanySlugAuthedWmsAllocationRoute,
    CompanySlugAuthedWmsInventoryRoute: CompanySlugAuthedWmsInventoryRoute,
    CompanySlugAuthedWmsIndexRoute: CompanySlugAuthedWmsIndexRoute,
    CompanySlugAuthedWmsOrdersIdRoute: CompanySlugAuthedWmsOrdersIdRoute,
    CompanySlugAuthedWmsOrdersIndexRoute: CompanySlugAuthedWmsOrdersIndexRoute,
  }

const CompanySlugAuthedWmsRouteRouteWithChildren =
  CompanySlugAuthedWmsRouteRoute._addFileChildren(
    CompanySlugAuthedWmsRouteRouteChildren,
  )

interface CompanySlugAuthedRouteChildren {
  CompanySlugAuthedHomeRouteRoute: typeof CompanySlugAuthedHomeRouteRouteWithChildren
  CompanySlugAuthedCrmRouteRoute: typeof CompanySlugAuthedCrmRouteRouteWithChildren
  CompanySlugAuthedErpRouteRoute: typeof CompanySlugAuthedErpRouteRouteWithChildren
  CompanySlugAuthedPlmRouteRoute: typeof CompanySlugAuthedPlmRouteRouteWithChildren
  CompanySlugAuthedPmRouteRoute: typeof CompanySlugAuthedPmRouteRouteWithChildren
  CompanySlugAuthedWmsRouteRoute: typeof CompanySlugAuthedWmsRouteRouteWithChildren
  CompanySlugAuthedAccountRoute: typeof CompanySlugAuthedAccountRoute
}

const CompanySlugAuthedRouteChildren: CompanySlugAuthedRouteChildren = {
  CompanySlugAuthedHomeRouteRoute: CompanySlugAuthedHomeRouteRouteWithChildren,
  CompanySlugAuthedCrmRouteRoute: CompanySlugAuthedCrmRouteRouteWithChildren,
  CompanySlugAuthedErpRouteRoute: CompanySlugAuthedErpRouteRouteWithChildren,
  CompanySlugAuthedPlmRouteRoute: CompanySlugAuthedPlmRouteRouteWithChildren,
  CompanySlugAuthedPmRouteRoute: CompanySlugAuthedPmRouteRouteWithChildren,
  CompanySlugAuthedWmsRouteRoute: CompanySlugAuthedWmsRouteRouteWithChildren,
  CompanySlugAuthedAccountRoute: CompanySlugAuthedAccountRoute,
}

const CompanySlugAuthedRouteWithChildren =
  CompanySlugAuthedRoute._addFileChildren(CompanySlugAuthedRouteChildren)

interface CompanySlugRouteRouteChildren {
  CompanySlugAuthedRoute: typeof CompanySlugAuthedRouteWithChildren
  CompanySlugAccessDeniedRoute: typeof CompanySlugAccessDeniedRoute
  CompanySlugErrorRoute: typeof CompanySlugErrorRoute
  CompanySlugLoginRoute: typeof CompanySlugLoginRoute
  CompanySlugAuthConfirmRoute: typeof CompanySlugAuthConfirmRoute
  CompanySlugAuthWorkosCallbackRoute: typeof CompanySlugAuthWorkosCallbackRoute
}

const CompanySlugRouteRouteChildren: CompanySlugRouteRouteChildren = {
  CompanySlugAuthedRoute: CompanySlugAuthedRouteWithChildren,
  CompanySlugAccessDeniedRoute: CompanySlugAccessDeniedRoute,
  CompanySlugErrorRoute: CompanySlugErrorRoute,
  CompanySlugLoginRoute: CompanySlugLoginRoute,
  CompanySlugAuthConfirmRoute: CompanySlugAuthConfirmRoute,
  CompanySlugAuthWorkosCallbackRoute: CompanySlugAuthWorkosCallbackRoute,
}

const CompanySlugRouteRouteWithChildren =
  CompanySlugRouteRoute._addFileChildren(CompanySlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CompanySlugRouteRoute: CompanySlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
