/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevShowcaseRouteImport } from './routes/dev/showcase'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth/update-password'
import { Route as AuthSignUpSuccessRouteImport } from './routes/auth/sign-up-success'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthedAppRouteRouteImport } from './routes/_authed/app/route'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/app/index'
import { Route as AuthedAppWorkspacesRouteImport } from './routes/_authed/app/workspaces'
import { Route as AuthedAppSettingsRouteImport } from './routes/_authed/app/settings'
import { Route as AuthedAppOrgOrgIdRouteRouteImport } from './routes/_authed/app/org/$orgId/route'
import { Route as AuthedAppOrgOrgIdUsersRouteImport } from './routes/_authed/app/org/$orgId/users'
import { Route as AuthedAppOrgOrgIdSettingsRouteImport } from './routes/_authed/app/org/$orgId/settings'
import { Route as AuthedAppOrgOrgIdDashboardRouteImport } from './routes/_authed/app/org/$orgId/dashboard'
import { Route as AuthedAppOrgOrgIdCompaniesRouteImport } from './routes/_authed/app/org/$orgId/companies'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevShowcaseRoute = DevShowcaseRouteImport.update({
  id: '/dev/showcase',
  path: '/dev/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpSuccessRoute = AuthSignUpSuccessRouteImport.update({
  id: '/auth/sign-up-success',
  path: '/auth/sign-up-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRouteRoute = AuthedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedAppWorkspacesRoute = AuthedAppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedAppSettingsRoute = AuthedAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedAppOrgOrgIdRouteRoute = AuthedAppOrgOrgIdRouteRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedAppOrgOrgIdUsersRoute = AuthedAppOrgOrgIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedAppOrgOrgIdRouteRoute,
} as any)
const AuthedAppOrgOrgIdSettingsRoute =
  AuthedAppOrgOrgIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedAppOrgOrgIdRouteRoute,
  } as any)
const AuthedAppOrgOrgIdDashboardRoute =
  AuthedAppOrgOrgIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedAppOrgOrgIdRouteRoute,
  } as any)
const AuthedAppOrgOrgIdCompaniesRoute =
  AuthedAppOrgOrgIdCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthedAppOrgOrgIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app': typeof AuthedAppRouteRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dev/showcase': typeof DevShowcaseRoute
  '/app/settings': typeof AuthedAppSettingsRoute
  '/app/workspaces': typeof AuthedAppWorkspacesRoute
  '/app/': typeof AuthedAppIndexRoute
  '/app/org/$orgId': typeof AuthedAppOrgOrgIdRouteRouteWithChildren
  '/app/org/$orgId/companies': typeof AuthedAppOrgOrgIdCompaniesRoute
  '/app/org/$orgId/dashboard': typeof AuthedAppOrgOrgIdDashboardRoute
  '/app/org/$orgId/settings': typeof AuthedAppOrgOrgIdSettingsRoute
  '/app/org/$orgId/users': typeof AuthedAppOrgOrgIdUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dev/showcase': typeof DevShowcaseRoute
  '/app/settings': typeof AuthedAppSettingsRoute
  '/app/workspaces': typeof AuthedAppWorkspacesRoute
  '/app': typeof AuthedAppIndexRoute
  '/app/org/$orgId': typeof AuthedAppOrgOrgIdRouteRouteWithChildren
  '/app/org/$orgId/companies': typeof AuthedAppOrgOrgIdCompaniesRoute
  '/app/org/$orgId/dashboard': typeof AuthedAppOrgOrgIdDashboardRoute
  '/app/org/$orgId/settings': typeof AuthedAppOrgOrgIdSettingsRoute
  '/app/org/$orgId/users': typeof AuthedAppOrgOrgIdUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_authed/app': typeof AuthedAppRouteRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/sign-up-success': typeof AuthSignUpSuccessRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dev/showcase': typeof DevShowcaseRoute
  '/_authed/app/settings': typeof AuthedAppSettingsRoute
  '/_authed/app/workspaces': typeof AuthedAppWorkspacesRoute
  '/_authed/app/': typeof AuthedAppIndexRoute
  '/_authed/app/org/$orgId': typeof AuthedAppOrgOrgIdRouteRouteWithChildren
  '/_authed/app/org/$orgId/companies': typeof AuthedAppOrgOrgIdCompaniesRoute
  '/_authed/app/org/$orgId/dashboard': typeof AuthedAppOrgOrgIdDashboardRoute
  '/_authed/app/org/$orgId/settings': typeof AuthedAppOrgOrgIdSettingsRoute
  '/_authed/app/org/$orgId/users': typeof AuthedAppOrgOrgIdUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/error'
    | '/login'
    | '/onboarding'
    | '/app'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/demo/tanstack-query'
    | '/dev/showcase'
    | '/app/settings'
    | '/app/workspaces'
    | '/app/'
    | '/app/org/$orgId'
    | '/app/org/$orgId/companies'
    | '/app/org/$orgId/dashboard'
    | '/app/org/$orgId/settings'
    | '/app/org/$orgId/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/error'
    | '/login'
    | '/onboarding'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/demo/tanstack-query'
    | '/dev/showcase'
    | '/app/settings'
    | '/app/workspaces'
    | '/app'
    | '/app/org/$orgId'
    | '/app/org/$orgId/companies'
    | '/app/org/$orgId/dashboard'
    | '/app/org/$orgId/settings'
    | '/app/org/$orgId/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/access-denied'
    | '/error'
    | '/login'
    | '/onboarding'
    | '/_authed/app'
    | '/auth/confirm'
    | '/auth/forgot-password'
    | '/auth/sign-up'
    | '/auth/sign-up-success'
    | '/auth/update-password'
    | '/demo/tanstack-query'
    | '/dev/showcase'
    | '/_authed/app/settings'
    | '/_authed/app/workspaces'
    | '/_authed/app/'
    | '/_authed/app/org/$orgId'
    | '/_authed/app/org/$orgId/companies'
    | '/_authed/app/org/$orgId/dashboard'
    | '/_authed/app/org/$orgId/settings'
    | '/_authed/app/org/$orgId/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthSignUpSuccessRoute: typeof AuthSignUpSuccessRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DevShowcaseRoute: typeof DevShowcaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/showcase': {
      id: '/dev/showcase'
      path: '/dev/showcase'
      fullPath: '/dev/showcase'
      preLoaderRoute: typeof DevShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/update-password': {
      id: '/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up-success': {
      id: '/auth/sign-up-success'
      path: '/auth/sign-up-success'
      fullPath: '/auth/sign-up-success'
      preLoaderRoute: typeof AuthSignUpSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app/': {
      id: '/_authed/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/app/workspaces': {
      id: '/_authed/app/workspaces'
      path: '/workspaces'
      fullPath: '/app/workspaces'
      preLoaderRoute: typeof AuthedAppWorkspacesRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/app/settings': {
      id: '/_authed/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthedAppSettingsRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/app/org/$orgId': {
      id: '/_authed/app/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/app/org/$orgId'
      preLoaderRoute: typeof AuthedAppOrgOrgIdRouteRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/app/org/$orgId/users': {
      id: '/_authed/app/org/$orgId/users'
      path: '/users'
      fullPath: '/app/org/$orgId/users'
      preLoaderRoute: typeof AuthedAppOrgOrgIdUsersRouteImport
      parentRoute: typeof AuthedAppOrgOrgIdRouteRoute
    }
    '/_authed/app/org/$orgId/settings': {
      id: '/_authed/app/org/$orgId/settings'
      path: '/settings'
      fullPath: '/app/org/$orgId/settings'
      preLoaderRoute: typeof AuthedAppOrgOrgIdSettingsRouteImport
      parentRoute: typeof AuthedAppOrgOrgIdRouteRoute
    }
    '/_authed/app/org/$orgId/dashboard': {
      id: '/_authed/app/org/$orgId/dashboard'
      path: '/dashboard'
      fullPath: '/app/org/$orgId/dashboard'
      preLoaderRoute: typeof AuthedAppOrgOrgIdDashboardRouteImport
      parentRoute: typeof AuthedAppOrgOrgIdRouteRoute
    }
    '/_authed/app/org/$orgId/companies': {
      id: '/_authed/app/org/$orgId/companies'
      path: '/companies'
      fullPath: '/app/org/$orgId/companies'
      preLoaderRoute: typeof AuthedAppOrgOrgIdCompaniesRouteImport
      parentRoute: typeof AuthedAppOrgOrgIdRouteRoute
    }
  }
}

interface AuthedAppOrgOrgIdRouteRouteChildren {
  AuthedAppOrgOrgIdCompaniesRoute: typeof AuthedAppOrgOrgIdCompaniesRoute
  AuthedAppOrgOrgIdDashboardRoute: typeof AuthedAppOrgOrgIdDashboardRoute
  AuthedAppOrgOrgIdSettingsRoute: typeof AuthedAppOrgOrgIdSettingsRoute
  AuthedAppOrgOrgIdUsersRoute: typeof AuthedAppOrgOrgIdUsersRoute
}

const AuthedAppOrgOrgIdRouteRouteChildren: AuthedAppOrgOrgIdRouteRouteChildren =
  {
    AuthedAppOrgOrgIdCompaniesRoute: AuthedAppOrgOrgIdCompaniesRoute,
    AuthedAppOrgOrgIdDashboardRoute: AuthedAppOrgOrgIdDashboardRoute,
    AuthedAppOrgOrgIdSettingsRoute: AuthedAppOrgOrgIdSettingsRoute,
    AuthedAppOrgOrgIdUsersRoute: AuthedAppOrgOrgIdUsersRoute,
  }

const AuthedAppOrgOrgIdRouteRouteWithChildren =
  AuthedAppOrgOrgIdRouteRoute._addFileChildren(
    AuthedAppOrgOrgIdRouteRouteChildren,
  )

interface AuthedAppRouteRouteChildren {
  AuthedAppSettingsRoute: typeof AuthedAppSettingsRoute
  AuthedAppWorkspacesRoute: typeof AuthedAppWorkspacesRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppOrgOrgIdRouteRoute: typeof AuthedAppOrgOrgIdRouteRouteWithChildren
}

const AuthedAppRouteRouteChildren: AuthedAppRouteRouteChildren = {
  AuthedAppSettingsRoute: AuthedAppSettingsRoute,
  AuthedAppWorkspacesRoute: AuthedAppWorkspacesRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppOrgOrgIdRouteRoute: AuthedAppOrgOrgIdRouteRouteWithChildren,
}

const AuthedAppRouteRouteWithChildren = AuthedAppRouteRoute._addFileChildren(
  AuthedAppRouteRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRouteRoute: typeof AuthedAppRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRouteRoute: AuthedAppRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSignUpSuccessRoute: AuthSignUpSuccessRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DevShowcaseRoute: DevShowcaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
